### ISSUE TITLE
.toArray() method is getting failed !

### ISSUE THREAD

**Issue by joshibhu** [ortexx/ip-cidr#10]
index.js -> toArray() method is getting failed in for loop for set of inputs.
e.g. -
I/P -> options = {from: 1500, limit: 600 } O/P -> array length = 600  
I/P -> options = {from: 600, limit: 1200 } O/P -> array length = 0  

On debugging, I noticed the following code snippet is getting failed due to incorrect comparison of jsbn BigInteger object with in for loop statements.

for (let i = info.from; i < info.from.add(info.to.compareTo(info.from)); i++) {
      let num = start.add(new BigInteger(i + ''));
      let ip = this.formatIP(this.ipAddressType.fromBigInteger(num), options);
      list.push(ip);
}

e.g. ->

a = new BigInteger('600');
b = new BigInteger('1200');
console.log(a < b)); // returns false

**Comment by ortexx** [comment]
Hey! Check out the new version. It should work well.

**Comment by joshibhu** [comment]
It is working now. Thanks for such a quick resolution.
