### ISSUE TITLE
Support IPv4-mapped IPv6 addresses (e.g. ::ffff:192.168.1.1)

### ISSUE THREAD

**Issue by thehappycoder** [ortexx/ip-cidr#16]
This library looks awesome but I found it was missing support for IPv4-mapped IPv6 addresses. https://whatismyipaddress.com/work-arounds

**Comment by ortexx** [comment]
Look at the new version. It should work.

**Comment by julianrutten** [comment]
It doesnt:
```        
const test = new IPCIDR('172.16.0.0/12');
console.log(test.contains('::ffff:172.23.0.7'));
console.log(test.contains('172.23.0.7'));
```
output:
```
false
true
```

Quick fix:
`string.replace(/^.*:/, '')`

For anybody finding this (in case its not resolved yet): `ip-range-check` lib does not have this issue and is lighter weight too.
