### ISSUE TITLE
IP address notation only is passing validation check

### ISSUE THREAD

**Issue by MartijnDunnebier** [ortexx/ip-cidr#19]
Hi @ortexx ,

First of all thank you for this handy tool! Unfortunately I run into an issue:

The isValid() function allows an IP address notation without CIDR to pass as valid CIDR. I know the underlying lib is [ip-address](https://github.com/beaugunderson/ip-address) and you use that for validation, but just an IP is not considered valid CIDR notation. Please check [this RFC at IETF](https://tools.ietf.org/html/rfc4632#section-3.1):

"In CIDR notation, a prefix is shown as a 4-octet quantity, just like a traditional IPv4 address or network number, followed by the "/" (slash) character, followed by a decimal value between 0 and 32 that describes the number of significant bits."

Am I using the validation function wrong maybe? I'm relatively new to programming so I'm not ruling that out :)

```typescript
const cidr = new IPCIDR('192.168.4.1');
return cidr.isValid();
```
The above returns true in my situation. Can you advise on this please? I'm on version 2.0.13. Thank you!

**Comment by ortexx** [comment]
Hey! We can consider it as a range with only one item. I am not sure how good or bad this behavior is. Does it affect your code someway?

**Comment by MartijnDunnebier** [comment]
Thank you for your reply! A single IP would be 192.168.4.1/32 in CIDR notation. It is affecting my code in the sense that I want the user to be enforced to enter an IP or range in CIDR notation, so that the backend can use that for auto assigning hosts. I could check this with a regex of course, and in case of just an IP add /32 to the IP string, but it would be better if the validation was done in this lib. At least in my opinion :)

**Comment by ortexx** [comment]
Ok. I changed it.

**Comment by MartijnDunnebier** [comment]
First off, thank you for your quick reponses and action! Sorry to bother you again @ortexx, I've tested 2.0.15 and I've noticed some possible issues:

1. Entering 'just' an IP, e.g. 192.168.4.1, returns NULL in the isValid() function. Was this intended?
2. When a valid CIDR is given as input, isValid() now returns an array. If this is the intention you might want to alter the return type of this function.

If you require me to open (2) new issues for this please let me know and I will take care of that. And if you need more info let me know and I will supply it.

**Comment by ortexx** [comment]
Strict is better, you are right! I've updated.

**Comment by MartijnDunnebier** [comment]
Tested 2.0.16, just the IP string still returns NULL, which translates to falsy, and a valid returns a /, which translates to truthy. So for my purpose this will work fine now. Again, thanks a million for your swift responses and updates!
