### ISSUE TITLE
Help on Integration with Angular 4 via Angular CLI

### ISSUE THREAD

**Issue by wizquest-labs** [ortexx/ip-cidr#2]
Hi,
I'm trying to integrate the library with Angular 4 project. Can you guide as to how can I do that? When I'm running Uglify.js, its showing me error, IPCIDR not found

**Comment by ortexx** [comment]
I am not sure about your issue - you gave not enough information, but I have published new version with some change. If you need the library in a bowser without any bundler using(webpack, browserify e.t.c),  you can get /dist/ip-cidr.js

**Comment by wizquest-labs** [comment]
When I try to run "ng serve --prod" it shows me error 

```
ERROR in vendor.ef7676925d13f45c0c55.bundle.js from UglifyJs
Unexpected token: name (IPCIDR) [vendor.ef7676925d13f45c0c55.bundle.js:30963,6]
```

I'm using the library in Angular Code

**Comment by ortexx** [comment]
The library use es6 syntax. You have to compile es6 to es5 (with babel, e.g) before to minify, because uglifyjs doesn't support es6 syntax. Or you can use another library for the minification.

**Comment by wizquest-labs** [comment]
Thanx that helped. Ran `babel src -d lib` to convert es6 to es5 code.

`node_modules/.bin/babel node_modules/ip-cidr -d node_modules/ip-cidr`
