### ISSUE TITLE
Feature Request: getCIDR

### ISSUE THREAD

**Issue by wiggitamoo** [ortexx/ip-cidr#22]
I would like the ability to get a list of CIDRs from a start and end IP address. 

Is this something you're open to adding to the library?

**Comment by ortexx** [comment]
I'll think about it. But in fact, you just need to convert your IP addresses to digital form and use pagination (from / limit) which has already been implemented.

**Comment by wiggitamoo** [comment]
Yes, I have already implemented it myself. I just thought it would be a nice feature for your library. if you want me to make a pull request you can point me in the right direction and I can help out.

**Comment by ortexx** [comment]
Yes, it might be useful. If it's not urgent, I'll add it a bit later myself, because there are some nuances to take it into account.

**Comment by ortexx** [comment]
I've implemented the feature in the master branch. You can take a look. If it's what you meant, then i'll release it. 
Now you can also use from/to passing ip addresses as well.

**Comment by wiggitamoo** [comment]
Yep, that's what I had in mind. I implemented it a little different, but I see what you mean about the nuances.
