### ISSUE TITLE
Support ES6 module loading

### ISSUE THREAD

**Issue by pilafmon** [ortexx/ip-cidr#24]
Add an ES6 module version of **ip-cidr** to prevent messages like:
```
WARNING in component.ts depends on 'ip-cidr'. CommonJS or AMD dependencies can
cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Maybe create an additional **.js** file containing lines similar to:
```js
import { ipAddress } from 'ip-address';
import { BigInteger } from 'jsbn';
...
export { IPCIDR };
```

**Comment by ortexx** [comment]
Why wouldn't use **allowedCommonJsDependencies** in your project?

**Comment by pilafmon** [comment]
Yep, we use that, but it would be cleaner to switch everything to the new ES module standard (even though it took the JavaScript world over a quarter century to finally settle on a standard and start actually using it).

**Comment by ortexx** [comment]
Yes, but its not a real issue now. Better just to change the code naturally when everyone switchs to v14+. I leave the issue to keep it in my mind.

**Comment by ortexx** [comment]
done
