### ISSUE TITLE
Returned BigIntegers do not pass `instanceOf BigInteger`

### ISSUE THREAD

**Issue by silverwind** [ortexx/ip-cidr#25]
```js
> const IPCIDR = require("ip-cidr");
> const {BigInteger} = require("jsbn");
> (new IPCIDR("::/0")).start({type: "bigInteger"}) instanceof BigInteger
false
```

Any idea why those do not pass this `instanceof` check? I'm currently using `val.constructor.name === 'BigInteger'` to workaround but this method doesn't play well with minifiers which often mangle function names.

**Comment by ortexx** [comment]
Sometimes I return an "ip-address" bigInteger that is a bit different (I'm not sure why, because it seems they also use jsbn). I released a new version with the same class everywhere.

**Comment by silverwind** [comment]
Thanks, `instanceof` check now works in all my cases with this change.
