### ISSUE TITLE
.prototype.toArray miss the last value of array

### ISSUE THREAD

**Issue by vitalikarabylo** [ortexx/ip-cidr#32]
We use this package to get the whole range of IPs, but the last IP of array is always missed.

We use it like this to get the whole range, but I guess the last value should be included by default:
const ips = [...cidr.toArray({from: cidr.start(), to: cidr.end()}), cidr.end()];

**Comment by ortexx** [comment]
It was done intentionally. Combination from/to means  **from <= x < to.**
If you want to get the whole range just skip any ending requirement ( cidr.toArray() ), or use **to + 1**.

**Comment by vitalikarabylo** [comment]
> It was done intentionally. Combination from/to means **from <= x < to.** If you want to get the whole range just skip any ending requirement ( cidr.toArray() ), or use **to + 1**.

Thank you. that works. Closing the issue.
