### ISSUE TITLE
Properties are not defined in the typings

### ISSUE THREAD

**Issue by maschwenk** [ortexx/ip-cidr#35]
https://github.com/ortexx/ip-cidr/blob/bfff0474ac7cc27dcb15c73f0426151a6a23d712/dist/ip-cidr.js#L14-L20

None of these properties exist on the typings. Only the class-level methods.

![image](https://user-images.githubusercontent.com/1264305/166553378-3aa8458b-4de9-4976-98a6-721c535c4bf0.png)

**Comment by ortexx** [comment]
https://github.com/ortexx/ip-cidr/pull/39
