### ISSUE TITLE
Missing method/property count of the IPs

### ISSUE THREAD

**Issue by tangent-q** [ortexx/ip-cidr#36]
Missing method/property count of the IPs of the CIDR without generating the array.

Expecting something like

```js
const cidr = new IPCIDR('255.255.255.128/24')
cidr.size // 256 (without generating the array cidr.toArray().length)
// or
cide.length // 256
```

**Comment by ortexx** [comment]
I added .size property. It is a big integer.

**Comment by tangent-q** [comment]
Working, thanks!

**Comment by tangent-q** [comment]
@ortexx could you add it in the type script please ?

**Comment by ortexx** [comment]
There are no other properties described now as well. I don't use and support TS, but if someone adds type changes I can accept PR

**Comment by tangent-q** [comment]
@ortexx https://github.com/ortexx/ip-cidr/pull/39

**Comment by ortexx** [comment]
done, thanks
