### ISSUE TITLE
IPCIDR may be not compatible with isValidAddress

### ISSUE THREAD

**Issue by tangent-q** [ortexx/ip-cidr#38]
Not sure if this is expected but `IPCIDR.isValidAddress` is not enough to ensure `new IPCIDR` will pass always.

```js
IPCIDR.isValidAddress('50.165.190.0') // true
new IPCIDR('50.165.190.0')
// Thrown:
// Error: Invalid CIDR address.
//    at new IPCIDR (/private/tmp/node_modules/ip-cidr/index.js:9:13)
```

If `isValidAddress` is meant only for IP the address without the mask, then would be nice to have `isValidCIDRAddress` as well.

**Comment by ortexx** [comment]
It is for both, either an ip or a cidr. The function is necessary to find out if the value is an address, not something else. IPCIDR constructor is not directly connected to that function. You just can't create an instance without bits specifying.

**Comment by tangent-q** [comment]
Got it @ortexx , thanks for the clarification. would be nice to have a `isValidCIDR` also then.
