### ISSUE TITLE
isValidAddress,... result false in v4

### ISSUE THREAD

**Issue by quyphan97** [ortexx/ip-cidr#48]
import IPCIDR from 'ip-cidr';
console.log(IPCIDR.isValidAddress('192.168.1.1')); // v4 -> false, v3 -> true
console.log(IPCIDR.isValidAddress('192.168.1.0/24')); // v4 -> false, v3 -> true

**Comment by ortexx** [comment]
Hey! I can't reproduce the issue. I get **true** for both your examples in v4 as well.

**Comment by quyphan97** [comment]
Yes, maybe I was wrong, I used it in reactjs so what's the error, I'm really sorry
![image](https://github.com/user-attachments/assets/065311cf-0c41-4a06-8117-01023bffacff)
