### ISSUE TITLE
Provide TypeScript Types

### ISSUE THREAD

**Issue by EvanDarwin** [ortexx/ip-cidr#6]
This package seems pretty simple, I'd be glad to contribute some TypeScript definitions to add the project!

**Comment by ortexx** [comment]
Hi! Sure.

**Comment by EvanDarwin** [comment]
@ortexx Changes are now in PR #7 -- I also updated the `chai` and `mocha` devDependencies because they have `npm audit` vulnerabilities, but should have no side effects since they're dev deps.

**Comment by ortexx** [comment]
Good work, thanks!

**Comment by EvanDarwin** [comment]
Glad to help! 😄
