### ISSUE TITLE
Your type definition for typescript is not working

### ISSUE THREAD

**Issue by Lexikus** [ortexx/ip-cidr#8]
By reading the javascript implementation 

```
class IPCIDR {
  constructor(cidr) {
  ...
}
```
You are expecting a class. Though, in the type definition you are exporting an interface with a constructor.

```
declare namespace ipcidr {
  ...
  interface IPCIDR {
        constructor(cidr: string): IPCIDR;
        ...
  }
}
```

How is this supposed to work?

**Comment by ortexx** [comment]
I've fixed. Take a look

**Comment by Lexikus** [comment]
Seem's to work. Ty for fixing it. :+1:
