### ISSUE TITLE
Negative Testing with 10.10.10.0

### ISSUE THREAD

**Issue by aaustin-1965** [ortexx/ip-cidr#9]
Hello,

I am using ip-cidr for a Node.js package. While negative testing my package, I initialized an ip-cidr object with a dotted-quad-decimal IP address '10.10.10.0' instead of a CIDR '10.10.10.0/24'.  I was expecting my object's isValid() method to return false, but it returns true.

I see that ip-cidr is relying on the ip-address npm package to determine if a valid address is present. Since a CIDR could be considered a subset of valid IP addresses, is this the intended behavior?  If a subnet mask isn't passed, does ip-cidr infer a default mask?

Thanks,
Andrew Austin

**Comment by ortexx** [comment]
Hello!
In this case we can consider an ip address as a range with the one item. I think it's ok.

**Comment by aaustin-1965** [comment]
That is reasonable. I updated my code.  Thanks.
